# Generated by Django 6.0.2 on 2026-03-29 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0002_email_subcriber"),
    ]

    operations = [
        migrations.AlterField(
            model_name="email",
            name="attachment",
            field=models.FileField(blank=True, upload_to="email_attachments/"),
        ),
    ]
