# Generated by Django 6.0.2 on 2026-04-01 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CompressImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_image", models.ImageField(upload_to="original_images/")),
                (
                    "quality",
                    models.IntegerField(
                        choices=[
                            (1, 1),
                            (11, 11),
                            (21, 21),
                            (31, 31),
                            (41, 41),
                            (51, 51),
                            (61, 61),
                            (71, 71),
                            (81, 81),
                            (91, 91),
                        ],
                        default=75,
                    ),
                ),
                (
                    "compressed_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="compressed_images/"
                    ),
                ),
                ("compressed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
