# Generated by Django 6.0.2 on 2026-04-01 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("image_compress", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="compressimage",
            name="quality",
            field=models.IntegerField(
                choices=[
                    (1, 1),
                    (11, 11),
                    (21, 21),
                    (31, 31),
                    (41, 41),
                    (51, 51),
                    (61, 61),
                    (71, 71),
                    (81, 81),
                    (91, 91),
                ],
                default=80,
            ),
        ),
    ]
