# Generated by Django 6.0.2 on 2026-03-08 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dataentry", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="roll_number",
            new_name="roll_no",
        ),
    ]
