# Generated by Django 6.0.2 on 2026-03-17 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dataentry", "0004_employee"),
    ]

    operations = [
        migrations.RenameField(
            model_name="employee",
            old_name="total_campensation",
            new_name="total_compensation",
        ),
    ]
