# Generated by Django 6.0.2 on 2026-04-03 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stockanalysis", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current_price", models.FloatField(blank=True, null=True)),
                ("price_change", models.FloatField(blank=True, null=True)),
                ("percentage_change", models.FloatField(blank=True, null=True)),
                ("previous_close", models.FloatField(blank=True, null=True)),
                ("week_52_high", models.FloatField(blank=True, null=True)),
                ("week_52_low", models.FloatField(blank=True, null=True)),
                ("market_cap", models.BigIntegerField(blank=True, null=True)),
                ("pe_ratio", models.FloatField(blank=True, null=True)),
                ("dividend_yield", models.FloatField(blank=True, null=True)),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data",
                        to="stockanalysis.stock",
                    ),
                ),
            ],
        ),
    ]
